### ISSUE TITLE
JSON files produced cannot be parsed with jq

### ISSUE THREAD

**Issue by adulau** [strontic/xcyclopedia#3]
Thanks for the initiative. It's great.

It seems that the JSON produced cannot be parsed with `jq` which is standard JSON parser.

~~~
cat strontic-xcyclopedia.json | jq .
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 22163, column 3776
~~~

**Comment by strontic** [comment]
Thanks. I'll look into this.

**Comment by josehelps** [comment]
Had a similar issue, not sure if related to jq, but tried parsing into python via `with open(STRONTIC_PATH, 'r') as file:` and it did not like the UTF chars at the start of the file `<U+FEFF>` .. setting encoding seemed to have done the trick: `with open(STRONTIC_PATH, 'r', encoding='utf-8-sig') as file:`,  now I am also seeing parsing issues:

```
Traceback (most recent call last):
  File "/Users/jhernandez/Research/malware/splunk/security_content/bin/macro_gen.py", line 43, in <module>
    main(sys.argv[1:])
  File "/Users/jhernandez/Research/malware/splunk/security_content/bin/macro_gen.py", line 35, in main
    generated_count = macro_gen(STRONTIC_PATH, REPO_PATH, VERBOSE)
  File "/Users/jhernandez/Research/malware/splunk/security_content/bin/macro_gen.py", line 13, in macro_gen
    strontic_objects = json.loads(file.read())
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 22163 column 70 (char 3414075)
```

seems like a different column than JQ though: 
```
└── # cat strontic-xcyclopedia.json | jq
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 22163, column 3776
```

**Comment by josehelps** [comment]
Actually looks like 
```
    with open(STRONTIC_PATH, 'r', encoding='utf-8-sig') as file:
        strontic_objects = json.load(file,strict=False)
```

does the trick in python 😄

**Comment by strontic** [comment]
This seems to be caused by special ASCII characters making their way into the JSON output. In this case, it's the ESC character (hex 1B, or \u001B) from Windows conhost.exe stdout. It appears that certain JSON parsers expect this to be escaped. I found other garbage characters coming from dash.exe that also cause jq to fail.

The issue appears related to #4 as well, which uses dos2unix.

Submitting a fix that will strip these characters...

**Comment by strontic** [comment]
@adulau Can you check if the issue is resolved?
